[package]
name = "sky-trie"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
postcard = { workspace = true, features = ["alloc"] }
futures.workspace = true
sky-types.workspace = true

[dev-dependencies]
anyhow.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros"] }
tokio-stream.workspace = true
