[package]
name = "sky-db"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
futures.workspace = true
async-stream.workspace = true
sky-trie.workspace = true
universal-hash.workspace = true
tokio = { workspace = true, features = ["macros"] }


[dev-dependencies]
tokio = { workspace = true, features = ["macros", "full"] }
