[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.102"
thiserror = "2.0.20"
tokio = { version = "1", features = ["sync", "rt", "time", "io-util"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tempfile = "3.27.0"
postcard = "1.1.3"
tokio-stream = "0.1.18"
futures = "0.3.32"
async-stream = "0.3.6"
log = "0.4.34"

sky-db = { path = "crates/sky-db" }
sky-server = { path = "crates/sky-server" }
sky-types = { path = "crates/sky-types", default-features = false }
universal-hash = { path = "crates/universal-hash" }

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
