[package]
name = "hamt2"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros"] }
serde.workspace = true
futures.workspace = true
async-stream.workspace = true
log = "0.4.34"
sky-trie.workspace = true
sky-types.workspace = true
universal-hash.workspace = true

[dev-dependencies]
tempfile.workspace = true
