[package]
name = "hamt2"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros"] }
serde.workspace = true
serde_json.workspace = true
redb.workspace = true
tempfile.workspace = true
postcard = { workspace = true, features = ["alloc"] }
lru.workspace = true
tokio-stream.workspace = true
futures.workspace = true
async-stream.workspace = true
