[package]
name = "sky-types"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
universal-hash.workspace = true
thiserror.workspace = true
futures.workspace = true
anyhow.workspace = true
postcard = { workspace = true, features = ["alloc"] }
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
tempfile.workspace = true
tokio-stream.workspace = true
