[package]
name = "sky-server"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
thiserror.workspace = true
sky-db.workspace = true
sky-types.workspace = true
sky-trie.workspace = true
log = "0.4.34"
serde = { version = "1.0.229", features = ["derive"] }
futures-util = "0.3.34"
tokio-stream = "0.1.19"
tokio-util = "0.7.19"

